# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/mapper/luks-9f940329-2a46-4253-a9cd-7013f1d9f216";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-9f940329-2a46-4253-a9cd-7013f1d9f216".device = "/dev/disk/by-uuid/9f940329-2a46-4253-a9cd-7013f1d9f216";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/82EA-C7C8";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  swapDevices = [
    {device = "/dev/mapper/luks-51ab5daa-82a9-449c-b83f-ab7c8014c0a4";}
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
